name: note_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_bloc: ^8.1.3
  bloc:
  hive: ^2.2.3
  path_provider: ^2.0.11
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  shared_preferences:

dev_dependencies:
  hive_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
